version: '3.8'
services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/furniture
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env.prod.database
    
      
      

volumes:
  postgres_data: