# Generated by Django 5.0.3 on 2024-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_filial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filial_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
