# Generated by Django 5.0.3 on 2024-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_worker',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
