# Generated by Django 5.0.3 on 2024-06-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_salary_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary_worker',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
