# Generated by Django 5.0.3 on 2024-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_salary_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_salary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_earnings',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
