# Generated by Django 5.0.3 on 2024-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_daily_salary_user_monthly_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_earnings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
