# Generated by Django 5.0.3 on 2024-06-04 19:10

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_daily_salary_alter_user_monthly_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.svg', null=True, upload_to='users-images/%Y/%  m/%d/', validators=[users.utils.validate_image]),
        ),
    ]
