# Generated by Django 5.0.3 on 2024-06-06 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_workstatics_remove_user_daily_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='worker_static',
        ),
        migrations.AddField(
            model_name='workstatics',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worker_static', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
