# Generated by Django 5.0.3 on 2024-06-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_worker_static_workstatics_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_worker',
            field=models.IntegerField(default=0),
        ),
    ]
