# Generated by Django 5.0.3 on 2024-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_monthly_earnings_alter_user_salary_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('worker', 'worker'), ('chief', 'chief'), ('guard', 'guard')], default='worker', max_length=100),
        ),
    ]
