# Generated by Django 5.0.3 on 2024-06-25 04:54

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.svg', upload_to='users-images/%Y/%m/%d/', validators=[users.utils.validate_image]),
        ),
    ]
