# Generated by Django 5.0.3 on 2024-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='category',
            field=models.CharField(choices=[('mahsulot', 'mahsulot'), ('homashyo', 'homashyo')], default='mahsulot', max_length=255),
        ),
    ]
