# Generated by Django 5.0.3 on 2024-05-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='payment',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ndc',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
