# Generated by Django 5.0.3 on 2024-05-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workerwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='category',
            field=models.CharField(choices=[('mahsulot', 'mahsulot'), ('homashyo', 'homashyo'), ('finished_product', 'finished_product')], default='mahsulot', max_length=255),
        ),
    ]
