# Generated by Django 5.0.3 on 2024-05-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_enter_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='measurement',
            field=models.CharField(choices=[('kg', 'kg'), ('m/2', 'm/2'), ('m', 'm'), ('piece', 'piece')], default='kg', max_length=100),
        ),
    ]
