# Generated by Django 5.0.3 on 2024-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_enter_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='measurement',
            field=models.CharField(choices=[('kg', 'kg'), ('m/2', 'm/2'), ('m', 'm')], default='kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='measurement',
            field=models.CharField(choices=[('kg', 'kg'), ('m/2', 'm/2'), ('m', 'm'), ('piece', 'piece')], default='kg', max_length=100),
        ),
    ]
