# Generated by Django 5.0.3 on 2024-05-23 10:59

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_enter_measurement_alter_order_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default='default_order.png', upload_to='order-images/%Y/%m/%d/', validators=[users.utils.validate_image]),
        ),
    ]
