# Generated by Django 5.0.3 on 2024-05-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NO_ACTIVE', 'no_active'), ('PENDING', 'pending'), ('SUCCESSFULLY', 'successfully'), ('COMBINE', 'COMBINE')], default='NO_ACTIVE', max_length=50),
        ),
    ]
