# Generated by Django 5.0.3 on 2024-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NO_ACTIVE', 'no_active'), ('PENDING', 'pending'), ('SUCCESSFULLY', 'successfully')], default='NO_ACTIVE', max_length=200),
        ),
        migrations.DeleteModel(
            name='Order_Status',
        ),
    ]
