# Generated by Django 5.0.3 on 2024-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_companyproduct_remove_workerproduct_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NO_ACTIVE', 'no_active'), ('PENDING', 'pending'), ('SUCCESSFULLY', 'successfully'), ('ONE_PENDING', 'ONE_PENDING')], default='NO_ACTIVE', max_length=200),
        ),
    ]
