# Generated by Django 5.0.3 on 2024-05-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enter',
            name='payment',
        ),
    ]
