# Generated by Django 5.0.3 on 2024-06-01 07:19

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_enter_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproduct',
            name='image',
            field=models.ImageField(default='default_order.png', upload_to='company-images/%d/', validators=[users.utils.validate_image]),
        ),
    ]
