# Generated by Django 5.0.3 on 2024-06-01 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_companyproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='STIR',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enter',
            name='company_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STIR', models.CharField(max_length=9)),
                ('company_name', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
