# Generated by Django 5.0.3 on 2024-06-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_enter_stir_enter_company_name_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='status',
            field=models.CharField(choices=[('MATERIAL_COST', 'MATERIAL_COST'), ('SALARY', 'SALARY'), ('TRANSPORT', 'TRANSPORT'), ('OTHER', 'OTHER')], default='MATERIAL_COST', max_length=204),
        ),
    ]
