# Generated by Django 5.0.3 on 2024-06-02 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NO_ACTIVE', 'no_active'), ('PENDING', 'pending'), ('SUCCESSFULLY', 'successfully'), ('ONE_PENDING', 'ONE_PENDING'), ('SOLD', 'SOLD')], default='NO_ACTIVE', max_length=200),
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('ndc', models.PositiveIntegerField(default=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
