# Generated by Django 5.0.3 on 2024-06-02 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_cost_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='STIR',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sold',
            name='company_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SoldCompanyName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('STIR', models.CharField(max_length=9)),
                ('company_name', models.CharField(max_length=1000)),
                ('sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sold')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
