# Generated by Django 5.0.3 on 2024-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_soldcompanyname_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldcompanyname',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soldcompanyname',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='soldcompanyname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
