# Generated by Django 5.0.3 on 2024-06-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_soldcompanyname_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='measurement',
            field=models.CharField(choices=[('dona', 'dona'), ('m3', 'm3'), ('m2', 'm2'), ('sum', 'sum'), ('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('complekt', 'complekt'), ('banka', 'banka'), ('list', 'list'), ('tonna', 'tonna'), ('pochka', 'pochka')], default='dona', max_length=100),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
