# Generated by Django 5.0.3 on 2024-06-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_order_measurement_delete_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='measurement',
            field=models.CharField(choices=[('dona', 'dona'), ('m3', 'm3'), ('m2', 'm2'), ('sum', 'sum'), ('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('complekt', 'complekt'), ('banka', 'banka'), ('list', 'list'), ('tonna', 'tonna'), ('pochka', 'pochka')], default='kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.companyproduct'),
        ),
    ]
