# Generated by Django 5.0.3 on 2024-06-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_enter_measurement_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
