# Generated by Django 5.0.3 on 2024-06-04 08:23

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default='default_order.png', upload_to='company-images/%d/', validators=[users.utils.validate_image]),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=1255),
        ),
    ]
