# Generated by Django 5.0.3 on 2024-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_order_image_order_price_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
