# Generated by Django 5.0.3 on 2024-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker_data',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
