# Generated by Django 5.0.3 on 2024-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_order_worker_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
