# Generated by Django 5.0.3 on 2024-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_finishedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='work_proses',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
