# Generated by Django 5.0.3 on 2024-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_finishedproduct_work_proses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='work_proses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_proses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
