# Generated by Django 5.0.3 on 2024-06-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_expense_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='finish_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.finishedproduct'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
