# Generated by Django 5.0.3 on 2024-06-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_sold_finish_product_alter_sold_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='order',
        ),
    ]
