# Generated by Django 5.0.3 on 2024-06-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_sold_created_at_sold_updated_at_alter_sold_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='sold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sold'),
        ),
        migrations.AlterField(
            model_name='companyname',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.enter'),
        ),
        migrations.DeleteModel(
            name='SoldCompanyName',
        ),
    ]
