# Generated by Django 5.0.3 on 2024-06-06 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_companyname_sold_alter_companyname_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='balance',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyname')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
