# Generated by Django 5.0.3 on 2024-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_companyname_balance_companybalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybalance',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='companyname',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
