# Generated by Django 5.0.3 on 2024-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_companybalance_price_alter_companyname_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter',
            name='payment_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sold',
            name='payment_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
