# Generated by Django 5.0.3 on 2024-06-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_enter_payment_price_sold_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='payment_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sold',
            name='payment_price',
            field=models.IntegerField(default=0),
        ),
    ]
