# Generated by Django 5.0.3 on 2024-06-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_enter_payment_price_alter_sold_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_names', to='core.enter'),
        ),
    ]
