# Generated by Django 5.0.3 on 2024-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_enter_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enter',
            name='payment_price',
            field=models.IntegerField(default=1),
        ),
    ]
