# Generated by Django 5.0.3 on 2024-06-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_expense_price_alter_expense_user_workerexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerexpense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workerexpense',
            name='status',
        ),
    ]
