# Generated by Django 5.0.3 on 2024-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_workerproductsendadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerproductsendadmin',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('NO_CONFIRMED', 'NO_CONFIRMED')], default='NO_CONFIRMED', max_length=100),
        ),
    ]
