# Generated by Django 5.0.3 on 2024-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_workerproductsendadmin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerproductsendadmin',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('NO_CONFIRMED', 'NO_CONFIRMED'), ('REJECT', 'REJECT')], default='NO_CONFIRMED', max_length=100),
        ),
    ]
