# Generated by Django 5.0.3 on 2024-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_workerproductsendadmin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerproduct',
            name='qty',
            field=models.FloatField(),
        ),
    ]
