# Generated by Django 5.0.3 on 2024-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_workerproduct_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerproduct',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workerproductsendadmin',
            name='qty',
            field=models.FloatField(),
        ),
    ]
