# Generated by Django 5.0.3 on 2024-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_workerproduct_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerproductget',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
