# Generated by Django 5.0.3 on 2024-06-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_orderassignment_testorder_orderassignment_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.testorder'),
        ),
        migrations.AlterField(
            model_name='testorder',
            name='workers',
            field=models.ManyToManyField(related_name='test_orders', through='core.OrderAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkerProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('finish_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.finishedproduct')),
            ],
        ),
    ]
