# Generated by Django 5.0.3 on 2024-06-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_orderassignment_order_alter_testorder_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerproductorder',
            name='product_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
