# Generated by Django 5.0.3 on 2024-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_workerproductorder_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerproductorder',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
