# Generated by Django 5.0.3 on 2024-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_workerproductorder_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='work_proses',
            field=models.IntegerField(),
        ),
    ]
