# Generated by Django 5.0.3 on 2024-06-18 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_finishedproduct_work_proses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='finish_product',
        ),
        migrations.AddField(
            model_name='sold',
            name='worker_product_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workerproductorder'),
        ),
    ]
