# Generated by Django 5.0.3 on 2024-06-20 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_sold_finish_product_sold_worker_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.enter'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
