# Generated by Django 5.0.3 on 2024-06-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_finishedproduct_product_alter_finishedproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='measurement',
            field=models.CharField(choices=[('dona', 'dona'), ('m3', 'm3'), ('m2', 'm2'), ('sum', 'sum'), ('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('m', 'm'), ('complekt', 'complekt'), ('banka', 'banka'), ('list', 'list'), ('tonna', 'tonna'), ('pochka', 'pochka')], default='kg', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='measurement',
            field=models.CharField(choices=[('dona', 'dona'), ('m3', 'm3'), ('m2', 'm2'), ('sum', 'sum'), ('kg', 'kg'), ('l', 'l'), ('m', 'm'), ('complekt', 'complekt'), ('banka', 'banka'), ('list', 'list'), ('tonna', 'tonna'), ('pochka', 'pochka'), ('g', 'g')], default='dona', max_length=100),
        ),
    ]
