# Generated by Django 5.0.3 on 2024-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_enter_measurement_alter_order_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybalance',
            name='dollar_course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
