# Generated by Django 5.0.3 on 2024-06-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_companybalance_dollar_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybalance',
            name='dollar_course',
            field=models.IntegerField(default=0),
        ),
    ]
