# Generated by Django 5.0.3 on 2024-06-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_companybalance_dollar_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('MATERIAL_COST', 'MATERIAL_COST'), ('SALARY', 'SALARY'), ('TRANSPORT', 'TRANSPORT'), ('DRIVER', 'DRIVER'), ('COOKER', 'COOKER'), ('OTHER', 'OTHER')], default='MATERIAL_COST', max_length=204),
        ),
    ]
