# Generated by Django 5.0.3 on 2024-06-25 10:18

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_companyproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproduct',
            name='image',
            field=models.ImageField(default='defualt_order.jpg', upload_to='company-images/%d/', validators=[users.utils.validate_image]),
        ),
    ]
